version: '3.8'

services:
  email-reader-console:
    build:
      context: ./email-reader-console
      dockerfile: Dockerfile
    volumes:
      - ./email-reader-console/logs:/app/logs
      - ./email-reader-console/data:/app/data
    env_file:
      - ./email-reader-console/.env
  email-reader-service:
    build:
      context: ./email-reader-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./email-reader-service/logs:/app/logs
      - ./email-reader-service/data:/app/data
    env_file:
      - ./email-reader-service/.env

  email-reader-ui:
    build:
      context: ./email-reader-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - email-reader-service
