version: '3.8'

services:
  email-reader-console:
    build:
      context: ./email-reader-console
      dockerfile: Dockerfile
    volumes:
      - ./email-reader-console/logs:/app/logs
      - ./email-reader-console/data:/app/data
    env_file:
      - ./email-reader-console/.env
  email-reader-service:
    build:
      context: ./email-reader-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./email-reader-service/logs:/app/logs
      - ./email-reader-service/data:/app/data
    env_file:
      - ./email-reader-service/.env

  email-reader-ui:
    build:
      context: ./email-reader-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - email-reader-service

  react-shell:
    build:
      context: ./react-shell
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - email-reader-ui
      - email-reader-service

  crewai-insight-service:
    build:
      context: ./crewai-insight-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./crewai-insight-service/logs:/app/logs
      - ./email-reader-service/data:/app/data/archives
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - CONFIG_PATH=/app/config/agent-config.xml
      - DATA_DIR=/app/data
      - OPENAI_API_KEY=NA
    depends_on:
      - email-reader-service
      - ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ollama:
    image: ollama/ollama:latest
    container_name: agentic-email-crew-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: always
