version: '3.8'

services:
  email-reader-console:
    build:
      context: ./email-reader-console
      dockerfile: Dockerfile
    volumes:
      - ./email-reader-console/logs:/app/logs
      - ./email-reader-console/data:/app/data
    env_file:
      - ./email-reader-console/.env
